# mode: -*- shell-script -*-
# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Common color definitions.
source ~/.colors

# Set the command prompt.
case "$TERM" in
  xterm*|rxvt*|screen)
    COLOR='$(if [[ $? = 0 ]]; then echo -en "\[${txtcya}\]"; else echo -en "\[${txtred}\]"; fi)'
    PS1="\[${txtgre}\]\u@\h \[${txtblu}\]\w\n${COLOR}\$\[${txtrst}\] "
    ;;
  *)
    PS1='\u@\h:\w\$ '
    ;;
esac


# Alias definitions.
alias cp='cp -i'
alias grep='grep --color=auto'
alias ls='ls --color=auto -Fh'
alias mv='mv -i'
alias rm='rm -i'
alias time=/usr/bin/time
alias grep='grep --color=auto'

# Turn on color output for all grep flavors.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias rgrep='rgrep --color=auto'

# Environment variables.
export EDITOR=emacs
export LESS=-iRS
export PAGER=less

# Use UTF-8 as the default locale.
export LC=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LESSCHARSET=utf-8

# Completion rules.
if [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi

# Site-specific customizations.
if [ -d ~/.site/ ]; then
   source ~/.site/bashrc
fi
